const LARGE_POPULATION = 1_000_000_000;
const LARGE_DIAMETER = 10_000;
const NUM_STARSHIPS_TO_DISPLAY = 3;

module.exports = {
  LARGE_POPULATION,
  LARGE_DIAMETER,
  NUM_STARSHIPS_TO_DISPLAY,
};